[2025-06-25T18:08:49.894+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_reddit_pipeline.s3_upload manual__2025-06-25T18:08:42.979795+00:00 [queued]>
[2025-06-25T18:08:49.900+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_reddit_pipeline.s3_upload manual__2025-06-25T18:08:42.979795+00:00 [queued]>
[2025-06-25T18:08:49.901+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2025-06-25T18:08:49.907+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): s3_upload> on 2025-06-25 18:08:42.979795+00:00
[2025-06-25T18:08:49.912+0000] {standard_task_runner.py:57} INFO - Started process 192 to run task
[2025-06-25T18:08:49.915+0000] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'etl_reddit_pipeline', 's3_upload', 'manual__2025-06-25T18:08:42.979795+00:00', '--job-id', '38', '--raw', '--subdir', 'DAGS_FOLDER/reddit_dag.py', '--cfg-path', '/tmp/tmplrm3725r']
[2025-06-25T18:08:49.917+0000] {standard_task_runner.py:85} INFO - Job 38: Subtask s3_upload
[2025-06-25T18:08:49.952+0000] {task_command.py:416} INFO - Running <TaskInstance: etl_reddit_pipeline.s3_upload manual__2025-06-25T18:08:42.979795+00:00 [running]> on host f892d2298fb9
[2025-06-25T18:08:50.001+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Paresh Jadhav' AIRFLOW_CTX_DAG_ID='etl_reddit_pipeline' AIRFLOW_CTX_TASK_ID='s3_upload' AIRFLOW_CTX_EXECUTION_DATE='2025-06-25T18:08:42.979795+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-06-25T18:08:42.979795+00:00'
[2025-06-25T18:08:50.010+0000] {logging_mixin.py:151} INFO - None
[2025-06-25T18:08:50.011+0000] {aws_etl.py:14} ERROR - module 's3fs' has no attribute 's3FileSystem'
[2025-06-25T18:08:50.012+0000] {aws_etl.py:25} ERROR - 'NoneType' object has no attribute 'exists'
[2025-06-25T18:08:50.012+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/pipelines/aws_s3_pipline.py", line 10, in upload_s3_pipeline
    upload_to_s3(s3, file_path, AWS_BUCKET_NAME, file_path.split('/')[-1])
AttributeError: 'NoneType' object has no attribute 'split'
[2025-06-25T18:08:50.020+0000] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=etl_reddit_pipeline, task_id=s3_upload, execution_date=20250625T180842, start_date=20250625T180849, end_date=20250625T180850
[2025-06-25T18:08:50.026+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 38 for task s3_upload ('NoneType' object has no attribute 'split'; 192)
[2025-06-25T18:08:50.047+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2025-06-25T18:08:50.059+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
