[2025-06-25T07:10:50.172+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_reddit_pipeline.reddit_extraction manual__2025-06-25T07:10:49.380427+00:00 [queued]>
[2025-06-25T07:10:50.177+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_reddit_pipeline.reddit_extraction manual__2025-06-25T07:10:49.380427+00:00 [queued]>
[2025-06-25T07:10:50.178+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2025-06-25T07:10:50.185+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): reddit_extraction> on 2025-06-25 07:10:49.380427+00:00
[2025-06-25T07:10:50.190+0000] {standard_task_runner.py:57} INFO - Started process 124 to run task
[2025-06-25T07:10:50.193+0000] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'etl_reddit_pipeline', 'reddit_extraction', 'manual__2025-06-25T07:10:49.380427+00:00', '--job-id', '20', '--raw', '--subdir', 'DAGS_FOLDER/reddit_dag.py', '--cfg-path', '/tmp/tmpmv_rktzw']
[2025-06-25T07:10:50.196+0000] {standard_task_runner.py:85} INFO - Job 20: Subtask reddit_extraction
[2025-06-25T07:10:50.234+0000] {task_command.py:416} INFO - Running <TaskInstance: etl_reddit_pipeline.reddit_extraction manual__2025-06-25T07:10:49.380427+00:00 [running]> on host f892d2298fb9
[2025-06-25T07:10:50.321+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Paresh Jadhav' AIRFLOW_CTX_DAG_ID='etl_reddit_pipeline' AIRFLOW_CTX_TASK_ID='reddit_extraction' AIRFLOW_CTX_EXECUTION_DATE='2025-06-25T07:10:49.380427+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-06-25T07:10:49.380427+00:00'
[2025-06-25T07:10:50.323+0000] {logging_mixin.py:151} WARNING - Version 7.7.1 of praw is outdated. Version 7.8.1 was released Friday October 25, 2024.
[2025-06-25T07:10:50.327+0000] {logging_mixin.py:151} INFO - Authenticated as: None
[2025-06-25T07:10:50.329+0000] {reddit_etl.py:18} INFO - connected to reddit!
[2025-06-25T07:10:51.500+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/pipelines/reddit_pipeline.py", line 8, in reddit_pipeline
    posts = extract_posts(reddit_instance,subreddit,timefilter,limt)
  File "/opt/airflow/etls/reddit_etl.py", line 33, in extract_posts
    for post in posts:
  File "/home/airflow/.local/lib/python3.9/site-packages/praw/models/listing/generator.py", line 63, in __next__
    self._next_batch()
  File "/home/airflow/.local/lib/python3.9/site-packages/praw/models/listing/generator.py", line 89, in _next_batch
    self._listing = self._reddit.get(self.url, params=self.params)
  File "/home/airflow/.local/lib/python3.9/site-packages/praw/util/deprecate_args.py", line 43, in wrapped
    return func(**dict(zip(_old_args, args)), **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/praw/reddit.py", line 712, in get
    return self._objectify_request(method="GET", params=params, path=path)
  File "/home/airflow/.local/lib/python3.9/site-packages/praw/reddit.py", line 517, in _objectify_request
    self.request(
  File "/home/airflow/.local/lib/python3.9/site-packages/praw/util/deprecate_args.py", line 43, in wrapped
    return func(**dict(zip(_old_args, args)), **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/praw/reddit.py", line 941, in request
    return self._core.request(
  File "/home/airflow/.local/lib/python3.9/site-packages/prawcore/sessions.py", line 328, in request
    return self._request_with_retries(
  File "/home/airflow/.local/lib/python3.9/site-packages/prawcore/sessions.py", line 267, in _request_with_retries
    raise self.STATUS_EXCEPTIONS[response.status_code](response)
prawcore.exceptions.Forbidden: received 403 HTTP response
[2025-06-25T07:10:51.516+0000] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=etl_reddit_pipeline, task_id=reddit_extraction, execution_date=20250625T071049, start_date=20250625T071050, end_date=20250625T071051
[2025-06-25T07:10:51.525+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 20 for task reddit_extraction (received 403 HTTP response; 124)
[2025-06-25T07:10:51.572+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2025-06-25T07:10:51.586+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
